#!/bin/csh
#SBATCH --job-name=QAS
#SBATCH --mem 100
#SBATCH --export=ALL                                                            
#SBATCH -N 1 # number of nodes
#SBATCH -n 10 # number of cores
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH -t 0-0:30 # time (D-HH:MM)
module load stellopt/gcc
mpiexec -n 10 /u/epaul/STELLOPT_gcc/bin/xstelloptv2 input.test
