#!/bin/bash
#SBATCH --job-name=QAS
#SBATCH --mem 100
#SBATCH --export=ALL                                                            
#SBATCH -N 1 # number of nodes
#SBATCH -n 5 # number of cores
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH -t 0-0:30 # time (D-HH:MM)

mpiexec -n 5 /p/focus/source/master/bin/xfocus hsx.input | tee output.txt
